name: Django CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: pzergling
          MYSQL_DATABASE: mysql
        ports: ["8888:3306"]
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create DB
        run: |
          mysql -h 127.0.0.1 --port 8888 -u root -ppzergling -e 'CREATE DATABASE IF NOT EXISTS test;'
      - name: Run Migrations
        run: python manage.py migrate
        env:
          DBENGINE: mysql.connector.django
          DBNAME: test
          DBUSER: root
          DBPASSWORD: pzergling
          DBHOST: 127.0.0.1
          DBPORT: 8888
      - name: Run Tests
        run: |
          pytest
        env:
          DBENGINE: mysql.connector.django
          DBNAME: test
          DBUSER: root
          DBPASSWORD: pzergling
          DBHOST: 127.0.0.1
          DBPORT: 8888
