name: Django CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mysql
        ports: ["3306:3306"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Grant privileges to MySQL test_user
        run: |
          mysql -u root -h 127.0.0.1 -p password -e "GRANT ALL PRIVILEGES ON mysql.* TO 'root'@'%' IDENTIFIED BY 'password';"
      - name: Run Migrations
        run: python manage.py migrate
        env:
          DBENGINE: mysql.connector.django
          DBNAME: mysql
          DBUSER: test_user
          DBPASSWORD: password
          DBHOST: 127.0.0.1
          DBPORT: $
      - name: Run Tests
        run: |
          python manage.py test
        env:
          DBENGINE: mysql.connector.django
          DBNAME: mysql
          DBUSER: test_user
          DBPASSWORD: password
          DBHOST: 127.0.0.1
          DBPORT: $
